---
title: "edgeR analysis tables"
output: pdf_document
---

```{r setup, echo = FALSE, messages = FALSE, warnings = FALSE, results = 'hide', include = FALSE}

      knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)

      library(tidyverse)
      library(kableExtra)

      
      load("objects/analysis_data.Rdata")
      load("objects/degs.Rdata")
      load("objects/pathways.Rdata")

```

```{r gopaths_d1}

      gopath_d1_l <- l_pairwise_gopathways_l[[1]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      gopath_d1_h <- l_pairwise_gopathways_h[[1]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      
      knitr::kable(cbind(gopath_d1_l, gopath_d1_h), format = "latex", booktabs = TRUE,
                   caption = "Day 1 GO Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(gopath_d1_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```

```{r rpaths_d1}

      rpath_d1_l <- l_pairwise_rpathways_l[[1]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      rpath_d1_h <- l_pairwise_rpathways_h[[1]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      
      knitr::kable(cbind(rpath_d1_l, rpath_d1_h), format = "latex", booktabs = TRUE,
                   caption = "Day 1 Reactome Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(rpath_d1_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```


```{r gopaths_d3}

      gopath_d3_l <- l_pairwise_gopathways_l[[2]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      gopath_d3_h <- l_pairwise_gopathways_h[[2]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      
      knitr::kable(cbind(gopath_d3_l, gopath_d3_h), format = "latex", booktabs = TRUE,
                   caption = "Day 3 GO Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(gopath_d3_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```

```{r rpaths_d3}

      rpath_d3_l <- l_pairwise_rpathways_l[[2]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      rpath_d3_h <- l_pairwise_rpathways_h[[2]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      
      knitr::kable(cbind(rpath_d3_l, rpath_d3_h), format = "latex", booktabs = TRUE,
                   caption = "Day 3 Reactome Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(rpath_d3_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```


```{r gopaths_d4}

      gopath_d4_l <- l_pairwise_gopathways_l[[3]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      gopath_d4_h <- l_pairwise_gopathways_h[[3]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      
      knitr::kable(cbind(gopath_d4_l, gopath_d4_h), format = "latex", booktabs = TRUE,
                   caption = "Day 4 GO Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(gopath_d4_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```

```{r rpaths_d4}

      rpath_d4_l <- l_pairwise_rpathways_l[[3]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      rpath_d4_h <- l_pairwise_rpathways_h[[3]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      
      knitr::kable(cbind(rpath_d4_l, rpath_d4_h), format = "latex", booktabs = TRUE,
                   caption = "Day 4 Reactome Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(rpath_d4_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```


```{r gopaths_d6}

      gopath_d6_l <- l_pairwise_gopathways_l[[4]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      gopath_d6_h <- l_pairwise_gopathways_h[[4]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      
      knitr::kable(cbind(gopath_d6_l, gopath_d6_h), format = "latex", booktabs = TRUE,
                   caption = "Day 6 GO Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(gopath_d6_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```

```{r rpaths_d6}

      rpath_d6_l <- l_pairwise_rpathways_l[[4]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      rpath_d6_h <- l_pairwise_rpathways_h[[4]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      
      knitr::kable(cbind(rpath_d6_l, rpath_d6_h), format = "latex", booktabs = TRUE,
                   caption = "Day 6 Reactome Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(rpath_d6_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```


```{r gopaths_d8}

      gopath_d8_l <- l_pairwise_gopathways_l[[5]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      gopath_d8_h <- l_pairwise_gopathways_h[[5]] %>% dplyr::select(c(Pathway, `p-value`)) %>% .[1:10,]
      
      knitr::kable(cbind(gopath_d8_l, gopath_d8_h), format = "latex", booktabs = TRUE,
                   caption = "Day 8 GO Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(gopath_d8_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```

```{r rpaths_d8}

      rpath_d8_l <- l_pairwise_rpathways_l[[5]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      rpath_d8_h <- l_pairwise_rpathways_h[[5]] %>% dplyr::select(c(Pathway, FDR)) %>% .[1:10,]
      
      knitr::kable(cbind(rpath_d8_l, rpath_d8_h), format = "latex", booktabs = TRUE,
                   caption = "Day 8 Reactome Pathways", linesep = "") %>% 

            kable_styling(font_size = 8, full_width = TRUE) %>% 
            
            add_header_above(c("Low inoculum" = 2, "High inoculum" = 2), bold = TRUE) %>%
            
            column_spec(c(1,3), width = "6.5cm") %>% 
            column_spec(c(2,4), width = "1.5cm") %>% 
            column_spec(2, border_right = TRUE) %>%
            
            row_spec(2:nrow(rpath_d8_l) - 1, hline_after = TRUE) %>% 
            row_spec(0, bold = TRUE)

```











