---
title: "edgeR Babesia RNAseq analysis"
output: pdf_document
---

```{r setup, include=FALSE}

      knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)

      library(purrr)
      library(tidyverse)
      library(data.table)
      library(plotly)
      library(ggrepel)
      library(edgeR)
      library(magrittr)
      library(stringi)
      library(biomaRt)
      library(topGO)
      library(GO.db)
      library(reactome.db)
      library(kableExtra)
      library(RColorBrewer)

      load("objects/analysis_data.Rdata")
      load("objects/degs.Rdata")
      load("objects/cluster_plots.Rdata")
      load("objects/pathways.Rdata")


      source("functions/volcano_plot.R")
      source("functions/pathways_plot.R")

```

# Pairwise day-by-day comparisons

```{r inocula, out.width = "100%"}

      df_inoculum <- data.frame("Low inoculum", "High inoculum")
      
      kable(df_inoculum, "latex", booktabs = TRUE, col.names = NULL, align = rep("c", 2)) %>% 
          column_spec(1:2, width = "8cm", border_left = TRUE, border_right = TRUE) %>% 
         kable_styling(font_size = 15)

```

```{r volc_d1, fig.show = "hold", fig.height = 6, out.width = "50%"}

      volcano_plot(l_pairwise_l[1])

      volcano_plot(l_pairwise_h[1])

```

```{r paths_d1, fig.show = "hold", fig.height = 12, out.width = "50%"}

      pathways_plot(l_gorpaths_l[1])

      pathways_plot(l_gorpaths_h[1])

```

```{r volc_d3, fig.show = "hold", fig.height = 6, out.width = "50%"}

      volcano_plot(l_pairwise_l[2])

      volcano_plot(l_pairwise_h[2])

```

```{r paths_d3, fig.show = "hold", fig.height = 12, out.width = "50%"}

      pathways_plot(l_gorpaths_l[2])

      pathways_plot(l_gorpaths_h[2])

```

```{r volc_d4, fig.show = "hold", fig.height = 6, out.width = "50%"}

      volcano_plot(l_pairwise_l[3])

      volcano_plot(l_pairwise_h[3])

```

```{r paths_d4, fig.show = "hold", fig.height = 12, out.width = "50%"}

      pathways_plot(l_gorpaths_l[3])

      pathways_plot(l_gorpaths_h[3])

```

```{r volc_d6, fig.show = "hold", fig.height = 6, out.width = "50%"}

      volcano_plot(l_pairwise_l[4])

      volcano_plot(l_pairwise_h[4])

```

```{r paths_d6, fig.show = "hold", fig.height = 12, out.width = "50%"}

      pathways_plot(l_gorpaths_l[4])

      pathways_plot(l_gorpaths_h[4])

```

```{r volc_d8, fig.show = "hold", fig.height = 6, out.width = "50%"}

      volcano_plot(l_pairwise_l[5])

      volcano_plot(l_pairwise_h[5])

```

```{r paths_d8, fig.show = "hold", fig.height = 12, out.width = "50%"}

      pathways_plot(l_gorpaths_l[5])

      pathways_plot(l_gorpaths_h[5])

```

# Clusters

```{r low_clusters}

      # Determine which observations belong to which cluster    
      my_clusters_l <- cutree(tree = hclust_l, k = 3) 
      
      df_corr_l$cluster <- my_clusters_l
      df_clust_l <- df_corr_l %>% dplyr::select(rowname, cluster)
      names(df_clust_l)[1] = "ensgene"
      
      # plot
      
         # calculate number of genes in each cluster
         df_n_l <- df_clust_l %>% dplyr::count(cluster)
         df_clust_l <- df_clust_l %>% left_join(df_n_l, by = "cluster")
         
         # add cluster to low genes
         df_avg_l2fc_l <- df_avg_l2fc[, c(1,grep("low_*", colnames(df_avg_l2fc)))] %>% left_join(df_clust_l, by = "ensgene")
         
         # pivot
         df_avg_l2fc_pivot_l <- df_avg_l2fc_l %>% pivot_longer(cols = 2:7, names_to = "day", values_to = "L2FC") %>% 
            mutate(day = substr(day, start = 5, stop = 5))
         
         df_clust_day_avgl2fc_l <- df_avg_l2fc_pivot_l %>%
            
            mutate(n = as.numeric(n)) %>% 
            
            group_by(cluster, n, day) %>%
            
            summarise(mean_L2FC = mean(L2FC),
                      stdev_L2FC = sd(L2FC)) %>% 
            
            mutate(error = qnorm(0.975)*stdev_L2FC/sqrt(n)) %>% 
            mutate(left = mean_L2FC - error, right = mean_L2FC + error) %>% 
            
            mutate(day = as.numeric(day)) %>% 
            mutate(cluster = as.factor(cluster)) %>% 
            
            mutate(cluster_n = paste0(cluster, sep = ", n = ", n))
         
         # plot all clusters
         df_clust_day_avgl2fc_l %>% ggplot() + 
               geom_line(aes(x = day, y = mean_L2FC, col = cluster), size = 2) + 
               geom_errorbar(aes(x = day, ymin = left, ymax = right), width = 0.2) +
               facet_wrap(~cluster_n) +
               theme_minimal() +
               ggtitle("Low inoculum clusters") +
               theme(legend.position = "none")
         
```

```{r degs_l}

   # create list of genes
   l_degs_l <- 1:max(df_all_degs_l$cluster) %>%
      purrr::map(~df_all_degs_l %>% filter(cluster == .x) %>% pull(geneID) %>% paste(collapse = ", "))
   
   names(l_degs_l) <- c(1:max(df_all_degs_l$cluster))
   
   # convert to df
   df_degs_in_clust_l <- bind_rows(l_degs_l) %>%
      pivot_longer(cols = 1:max(df_all_degs_l$cluster), names_to = "cluster", values_to = "geneID")
   
   # pivot
   df_degs_in_clust_l <- df_degs_in_clust_l %>% pivot_wider(names_from = cluster, values_from = geneID)
   
   # print df
   kable(df_degs_in_clust_l, "latex", booktabs = TRUE, align = rep("c", 3)) %>% 
      column_spec(1:3, width = "5.1cm", border_left = TRUE, border_right = TRUE) %>% 
      kable_styling(font_size = 8)


```

```{r high_clusters}

      # Determine which observations belong to which cluster    
      my_clusters_h <- cutree(tree = hclust_h, k = 3) 
      
      df_corr_h$cluster <- my_clusters_h
      df_clust_h <- df_corr_h %>% dplyr::select(rowname, cluster)
      names(df_clust_h)[1] = "ensgene"
      
      # plot
      
         # calculate number of genes in each cluster
         df_n_h <- df_clust_h %>% dplyr::count(cluster)
         df_clust_h <- df_clust_h %>% left_join(df_n_h, by = "cluster")
         
         # add cluster to low genes
         df_avg_l2fc_h <- df_avg_l2fc[, c(1,grep("high_*", colnames(df_avg_l2fc)))] %>% left_join(df_clust_h, by = "ensgene")
         
         # pivot
         df_avg_l2fc_pivot_h <- df_avg_l2fc_h %>% pivot_longer(cols = 2:7, names_to = "day", values_to = "L2FC") %>% 
            mutate(day = substr(day, start = 6, stop = 6))
         
         df_clust_day_avgl2fc_h <- df_avg_l2fc_pivot_h %>%
            
            mutate(n = as.numeric(n)) %>% 
            
            group_by(cluster, n, day) %>%
            
            summarise(mean_L2FC = mean(L2FC),
                      stdev_L2FC = sd(L2FC)) %>% 
            
            mutate(error = qnorm(0.975)*stdev_L2FC/sqrt(n)) %>% 
            mutate(left = mean_L2FC - error, right = mean_L2FC + error) %>% 
            
            mutate(day = as.numeric(day)) %>% 
            mutate(cluster = as.factor(cluster)) %>% 
            
            mutate(cluster_n = paste0(cluster, sep = ", n = ", n))
         
         
         # plot all clusters
         df_clust_day_avgl2fc_h %>% ggplot() + 
               geom_line(aes(x = day, y = mean_L2FC, col = cluster), size = 2) + 
               geom_errorbar(aes(x = day, ymin = left, ymax = right), width = 0.2) +
               facet_wrap(~cluster_n) +
               theme_minimal() +
               ggtitle("High inoculum clusters") +
               theme(legend.position = "none")
         

```

```{r degs_h}

   # create list of genes
   l_degs_h <- 1:max(df_all_degs_h$cluster) %>%
      purrr::map(~df_all_degs_h %>% filter(cluster == .x) %>% pull(geneID) %>% paste(collapse = ", "))
   
   names(l_degs_h) <- c(1:max(df_all_degs_h$cluster))
   
   # convert to df
   df_degs_in_clust_h <- bind_rows(l_degs_h) %>%
      pivot_longer(cols = 1:max(df_all_degs_h$cluster), names_to = "cluster", values_to = "geneID")
   
   # pivot
   df_degs_in_clust_h <- df_degs_in_clust_h %>% pivot_wider(names_from = cluster, values_from = geneID)
   
   # print df
   kable(df_degs_in_clust_h, "latex", booktabs = TRUE, align = rep("c", 3)) %>% 
      column_spec(1:3, width = "5.1cm", border_left = TRUE, border_right = TRUE) %>% 
      kable_styling(font_size = 8)


```

### Overlapping DEGs

```{r overlap_genes}

   kable(df_all_degs, "latex", booktabs = TRUE, align = rep("l", 4), linesep = "") %>% 
      column_spec(1, width = "3.5cm", border_left = TRUE, border_right = TRUE) %>% 
      column_spec(2:4, width = "1.7cm", border_left = TRUE, border_right = TRUE) %>% 
      kable_styling(font_size = 8)


```









